### ISSUE TITLE
[BUG] 在构建的时候会报错  java.lang.String can't cast to be java.lang.String[]

### ISSUE THREAD

**Issue by pengshuangbao** [hairless/plink#100]
**描述一下 bug**
简单的描述一下bug
在构建的时候会报错  java.lang.String can't cast to be java.lang.String[]
原因是因为这里下面截图中还要又一个子级的<descriptor></descriptor> 的，而源码中直接写成 <descriptors>,我本地改过来就可以了。

** 使用的Plink版本**
例：0.1.0

**重现过程**
具体的重现步骤:
1. 哪个页面/模块 '...'
2. 点击了 'clean install"
3. 看到了xxx错误

**屏幕截图**
如果有的话，请贴一下截图帮助我们更快的定位问题
![image](https://user-images.githubusercontent.com/16523697/90220073-0ca79480-de3a-11ea-8cc6-488091b8ad86.png)

**其他内容**
可添加任何关于bug的其他内容到此处

**Comment by sllence** [comment]
哪个tag或分支，有报错的信息吗

**Comment by pengshuangbao** [comment]
> 哪个tag或分支，有报错的信息吗

master 分支 ，报错信息 
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (make-assembly) on project plink-dist: Unable to parse configuration of mojo org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single for parameter descriptors: Cannot assign configuration entry 'descriptors' with value 'src/main/assembly/assembly.xml' of type java.lang.String to property of type java.lang.String[] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by sllence** [comment]
确定是mater吗，我这没有复现，如果是想测试0.1的话可直接下载压缩包
https://github.com/hairless/plink/releases/download/release-0.1.0/plink-0.1.0-bin.tar.gz

**Comment by sllence** [comment]
这个也可能和maven的版本有关系，我提个pr修复一下
