### ISSUE TITLE
Plink v0.1 dev plan items

### ISSUE THREAD

**Issue by wangyangting** [hairless/plink#17]
## v0.1 dev plan items
1. 原型  
2. 前端
    1. 作业管理
        1. 作业列表
            1. 新建作业
            2. 查询作业
            3. 作业启动/批量
            4. 作业重启/批量
            5. 作业停止/批量
            6. 作业删除/批量
        2. 实例列表
            1. 查询实例
            2. 实例详情
            3. 删除实例
    2. 作业详情
        1. 配置详情
        2. 作业启动
        3. 作业重启
        4. 作业停止
        5. 作业删除
        6. 实例列表(单任务维度)
    3. 作业编辑
        1. 配置编辑
        2. 上传jar
        2. jar列表
3. 后端
   1. 接口
        1. 新建作业接口
        2. 更新作业接口
        3. 查询作业接口
        4. 删除作业接口
        5. 启动作业接口
        6. 重启作业接口
        7. 停止作业接口
        8. 文件上传接口(Jar)
        9. 文件名获取接口
    2. 定时任务
        1. 作业状态轮询
        2. 定时提交新建实例(待确认)

## 领取任务的评论模板
> 注 : 要参与一起贡献的，评论后请加下面的 QQ 群.
如 : 
1. 前端 / 作业列表
2. 前端 / 作业管理 / 作业列表 / 作业启动
3. 后端 / 启动作业接口

## 联系方式
* QQ 群 : 602995595

**Comment by wangyangting** [comment]
前端 / 作业管理 / 作业列表
前端 / 作业管理 / 实例列表

**Comment by sllence** [comment]
all done
