### ISSUE TITLE
Docker Pull has an error

### ISSUE THREAD

**Issue by zhisheng17** [hairless/plink#89]
➜  ~ docker pull registry.cn-hangzhou.aliyuncs.com/hairless/plink:master
Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/hairless/plink:master not found

**Comment by sllence** [comment]
Thank you for reminding，please use plink:0.1.0 instead，I will fix it in docs

**Comment by sllence** [comment]
@wangyangting please add ‘latest’ version for docker hub，and update docs

**Comment by sllence** [comment]
fix
